google-blockly/README.md :
	wget -O "jeter.zip" "https://github.com/google/blockly/zipball/master"
	unzip jeter.zip
	rm jeter.zip
	mv google-blockly-* "google-blockly"
	touch -c $@
clean:
	rm -rf google-blockly
